# Generated by Django 4.0 on 2022-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0010_patients_diabeteschance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiabetesChance', models.BooleanField()),
                ('Hypoxia', models.BooleanField()),
                ('Hypothermia', models.BooleanField()),
                ('Fever', models.BooleanField()),
                ('username', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='patients',
            name='DiabetesChance',
        ),
    ]
