# Generated by Django 4.0 on 2022-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0011_conditions_remove_patients_diabeteschance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditions',
            name='id',
        ),
        migrations.AlterField(
            model_name='conditions',
            name='username',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
