# Generated by Django 4.0 on 2022-04-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0012_remove_conditions_id_alter_conditions_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='HighPulse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='DiabetesChance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='Fever',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='Hypothermia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='Hypoxia',
            field=models.BooleanField(default=False),
        ),
    ]
