# Generated by Django 4.0 on 2022-04-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0013_conditions_highpulse_alter_conditions_diabeteschance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='Alert',
            field=models.BooleanField(default=False),
        ),
    ]
