# Generated by Django 4.0 on 2022-04-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0014_conditions_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='Pedigree',
            field=models.FloatField(default=0.5),
        ),
    ]
